# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Maxence Aïci
tagline:          'A Jekyll theme'
description:      "A CS Student's blog "
url:              http://mininao.github.io
baseurl:          /

author:
  name:           'Maxence Aïci'
  url:            https://maxence.aici.me

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/mininao/
